SSR Pandora
Human-Connection/API pull request #9
Opened 2018-03-02 13:58 UTC by appinteractive

2018-03-02 15:11 UTC, chrisSCM requested changes
If possible, I would try and have just one source for the email template, not three! (in the sense of DRY)

Lots of typos in there, please see my comments!

2018-03-02 15:11 UTC, chrisSCM commented on email-templates/account/invite/de/html.hbs
> +                    Hallo {{ name }}, bitte bestädige deine E-Mail Adresse durch klick auf den unteren Link.
Hallo {{ name }}, bitte bestätige deine E-Mail-Adresse durch Klick auf den unteren Link.

2018-03-02 15:11 UTC, chrisSCM commented on email-templates/account/invite/de/html.hbs
> +                    Es ist wichtig das wir deine Korrekte E-Mail Adresse um dein Konto zu schützen
Es ist wichtig, dass wir deine korrekte E-Mail-Adresse haben, um dein Konto zu schützen.

2018-03-02 15:11 UTC, chrisSCM commented on email-templates/account/invite/de/html.hbs
> +                    <a href="{{ link }}" class="btn-primary" itemprop="url">Bestätige deine E-Mail Adresse</a>
"E-Mail-Adresse" immer mit Bindestrich!

2018-03-02 15:11 UTC, chrisSCM commented on email-templates/account/invite/de/subject.hbs
> +Bestätige deine E-Mail Adresse
"E-Mail-Adresse" immer mit Bindestrich!

2018-03-02 15:11 UTC, chrisSCM commented on email-templates/account/invite/de/text.hbs
> +Bitte bestätige deine E-Mail Adresse
"E-Mail-Adresse" immer mit Bindestrich!

2018-03-02 15:11 UTC, chrisSCM commented on email-templates/account/invite/de/text.hbs
> +Es ist wichtig das wir deine Korrekte E-Mail Adresse um dein Konto zu schützen.
Selber Text wie oben?! Mit denselben Fehlern ;-)

2018-03-02 15:11 UTC, chrisSCM commented on email-templates/account/verify-email/de/html.hbs
> +                    <h1 class="aligncenter">Bestätige deine E-Mail Adresse</h1>
...und nochmal....warum gibt es das alles dreimal?

2018-03-04 18:24 UTC, appinteractive commented on email-templates/account/verify-email/de/html.hbs
> +                    <h1 class="aligncenter">Bestätige deine E-Mail Adresse</h1>
Hey du, hast du sonst Textvorschläge?

2018-03-12 16:16 UTC, merged